/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthVerify
 */
export interface AuthVerify {
  /**
   *
   * @type {string}
   * @memberof AuthVerify
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof AuthVerify
   */
  created_at?: string | null;
}
