/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * General error for regular HTTP status codes
 * @export
 * @interface GeneralError
 */
export interface GeneralError {
  /**
   *
   * @type {number}
   * @memberof GeneralError
   */
  status: number;
  /**
   *
   * @type {string}
   * @memberof GeneralError
   */
  message: string;
}
