/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model to represent group
 * @export
 * @interface Group
 */
export interface Group {
  /**
   *
   * @type {string}
   * @memberof Group
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Group
   */
  slug?: string | null;
  /**
   *
   * @type {string}
   * @memberof Group
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof Group
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof Group
   */
  updated_at?: string;
}
