/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad, Etherpad for markdown with Go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { User } from "./user";
// May contain unused imports in some cases
// @ts-ignore
import type { UserGroup } from "./user-group";

/**
 *
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
  /**
   *
   * @type {number}
   * @memberof InlineObject4
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject4
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject4
   */
  offset: number;
  /**
   *
   * @type {User}
   * @memberof InlineObject4
   */
  user?: User;
  /**
   *
   * @type {Array<UserGroup>}
   * @memberof InlineObject4
   */
  groups: Array<UserGroup>;
}
