/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PermitUserGroupRequest
 */
export interface PermitUserGroupRequest {
  /**
   *
   * @type {string}
   * @memberof PermitUserGroupRequest
   */
  group: string;
  /**
   *
   * @type {string}
   * @memberof PermitUserGroupRequest
   */
  perm: string;
}
