/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad, Etherpad for markdown with Go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model to represent auth provider
 * @export
 * @interface Provider
 */
export interface Provider {
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  driver?: string;
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  display?: string;
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  icon?: string;
}
