/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad, Etherpad for markdown with go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UserTeam } from "./user-team";

/**
 * Model to represent team
 * @export
 * @interface Team
 */
export interface Team {
  /**
   *
   * @type {string}
   * @memberof Team
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  slug?: string | null;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  updated_at?: string;
  /**
   *
   * @type {Array<UserTeam>}
   * @memberof Team
   */
  users?: Array<UserTeam> | null;
}
