/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Team
 */
export interface Team {
  /**
   *
   * @type {string}
   * @memberof Team
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  slug?: string;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof Team
   */
  updated_at?: string;
}
