/* tslint:disable */
/* eslint-disable */
/**
 * Gopad OpenAPI
 * API definition for Gopad, Etherpad for markdown with Go
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: gopad@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UserAuth } from "./user-auth";

/**
 * Model to represent user
 */
export interface User {
  id?: string;
  username?: string | null;
  password?: string | null;
  email?: string | null;
  fullname?: string | null;
  profile?: string | null;
  admin?: boolean | null;
  active?: boolean | null;
  created_at?: string;
  updated_at?: string;
  auths?: Array<UserAuth> | null;
}
